---
- name: POST to Tower API
  hosts: webserver-ansar
  vars:
    job_template_id: 26
 
  tasks:
    - name: Invoke download Job ansar-template-ii
      uri:
        url: https://18.216.19.92/api/v2/job_templates/26/launch/
       #register: test
        method: POST
        user: admin
        password: ansible@123
        validate_certs: no
      # body_format: json
        status_code: 201
        validate_certs: no 
